service: serverless-dynamodb-tutorials

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: personal
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:ap-south-1:594108745002:table/developer_essentials

functions:
  add_data:
    handler: handler.add_data
    events:
      - http:
          path: /api/items/add
          method: POST
          cors: true

# Ref: creation rules : https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.CreateTable.html
# Ref: Supported Data types: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html
resources:
  Resources:
    MyFirstTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: developer_essentials
        AttributeDefinitions:
          - AttributeName: employee_email
            AttributeType: S
          - AttributeName: designation
            AttributeType: S
        KeySchema:
          - AttributeName: employee_email
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: byDesignation
            KeySchema:
              - AttributeName: designation 
                KeyType: HASH
            Projection:
                ProjectionType: "ALL"  
        BillingMode: PAY_PER_REQUEST          
          
                    




        