service: serverless-sns-tutorials

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: personal
  region: ap-south-1
  iam:
    role:
      statements: 
        - Effect: Allow
          Action: 
            - 'sns:SetSMSAttributes'
            - 'sns:Publish'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'logs:CreateLogStream'
            - 'logs:CreateLogGroup'
          Resource: arn:aws:logs:ap-south-1:594108745002:log-group:/aws/lambda/serverless-sns-tutorials-dev*:*
functions:
  send_sms:
    handler: handler.send_sms
    events:
      - http:
          path: newsletter/send-sms
          method: POST
          cors: true
      - sns:
          arn: !Ref SuperTopic
          topicName: CustomTopic    

  create_topic:
    handler: handler.create_topic
    events:
      - http:
          path: newsletter/create-newsletter
          method: POST
          cors: true
  subscribe:
    handler: handler.subscribe_to_newsletter
    events:
      - http:
          path: newsletter/subscribe
          method: POST
          cors: true    
  publish:
    handler: handler.publish_to_newsletter
    events:
      - http:
          path: newsletter/publish
          method: POST
          cors: true                 

resources:
  Resources:
    SuperTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CustomTopic