service: serverless-sns-tutorials

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: personal
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements: 
        - Effect: Allow
          Action: 
            - 'sns:SetSMSAttributes'
            - 'sns:Publish'
          Resource: '*'
        - Effect: Allow
          Action: 'ses:*'
          Resource: '*'

custom:
  SUBSCRIBERS_DDB_TABLE: SubscribersDDBTable-${self:provider.stage}

functions:
  send_sms:
    handler: handler.send_sms
    events:
      - http:
          path: newsletter/send-sms
          method: POST
          cors: true   

  create_topic:
    handler: handler.create_topic
    events:
      - http:
          path: newsletter/create-newsletter
          method: POST
          cors: true

  subscribe:
    handler: handler.subscribe_to_newsletter
    events:
      - http:
          path: newsletter/subscribe
          method: POST
          cors: true    
          
  publish:
    handler: handler.publish_to_newsletter
    events:
      - http:
          path: newsletter/publish
          method: POST
          cors: true           
      - sns:
          arn: !Ref NewsLetterTopic
          topicName: Newsletter-${self:provider.stage} 
    environment:
      DDB_TABLE_NAME: ${self:custom.SUBSCRIBERS_DDB_TABLE}      


resources:
  Resources:
    NewsLetterTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: Newsletter-${self:provider.stage}
    SubscribersDDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubscribersDDBTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: news_letter
            AttributeType:  S
          - AttributeName: admin_email
            AttributeType:  S  
        KeySchema:
          - AttributeName: news_letter
            KeyType:  Hash    
          - AttributeName: admin_email
            KeyType:  Hash  
        GlobalSecondaryIndexes:
          - IndexName: ByNewsLetter
            KeySchema:
              - AttributeName: news_letter
                KeyType: HASH
            Projection:
              ProjectionType: "ALL"    
        BillingMode: PAY_PER_REQUEST    